spring:
  application:
    name: service-websocket
  profiles:
    active: websocket

server:
  port: ${SERVER_PORT:9900}

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://admin:admin@localhost:8000/eureka/}
  instance:
    health-check-url-path: ${management.context-path}/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      cluster: study
      instanceId : ${APPLICATION_INSTANCE_ID:${spring.application.name}:${spring.application.instance_id:${server.port}}}

